# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
loom.platform=neoforge
# Mod Metadata
group=dev.sisby
user=sisby-folk
slug=mcqoy
modId=mcqoy
modName=Barebones McQoy
modDescription=A minimal compatibility layer that generates YACL configuration screens for QConfig mods.
authors=Sisby folk
contributors=cassiancc
license=EUPL-1.2
# Mod Version
modVersion=0.3.3
# Branch Metadata
branchName=neo-1.21
compatibleVersions=1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6
compatibleLoaders=neoforge
