name: Release

on:
  release:
    types:
      - published

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - name: Gradle Build
        run: ./gradlew build

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'build/libs/*.jar, !build/libs/*-sources.jar'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar

      - name: Maven Publish
        run: ./gradlew publish

      - name: Github Publish
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-sources.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modrinth Publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}
        if: ${{ env.MODRINTH_TOKEN != '' }}
        run: |
          ./gradlew modrinth
          ./gradlew modrinthSyncBody
